### PR TITLE
Implemented lifecycle status in the nodes

### PR DESCRIPTION
**Pull request by unaipme**

### CODE REVIEW

**Comment by aitor-gamarra** [comment]
When a wrong Connection String is used on the IoTHub node, it tries to reconnect and it should just enter an error status.

**Comment by aitor-gamarra** [comment]
When using a wrong connection string, if the connection string is corrected and the flow deployed, the logs still show that the device is trying to reconnect.

**Comment by unaipme** [comment]
@aitor-gamarra the two issues you mention have been fixed by implementing connection string validation at the node level. please feel free to review the code and (why not) approve the PR

**Review by aitor-gamarra — APPROVED** [review]
I love it

**Pull request merged**
