### PR TITLE
Implemented sensitive data as credentials

### PR DESCRIPTION
**Pull request by unaipme**
The `sasConnectionString` of the Blob Storage node, and the device connection string of the IotHub node are no longer stored in plain text on the _flow.json_ file. Some other cleanup, such as redundant imports and such, have been performed too.

### CODE REVIEW

**Review by sakur33 — APPROVED** [review]

**Comment by aitor-gamarra** [comment]
Missing version bump in package.json

**Review by bittorala — APPROVED** [review]
Works well in both nodes! We will now create the work items related to this change in the library :)

**Comment by aitor-gamarra** [comment]
pacakge-lock.json outdated (not only on this PR!) @bittorala the `package-lock`s are after us

**Comment by unaipme** [comment]
both issues mentioned by @aitor-gamarra are fixed already, this is ready to go when they approve the request

**Review by aitor-gamarra — APPROVED** [review]

**Pull request merged**
